### PR TITLE
Replace jwt with jose 

### PR DESCRIPTION
**Pull request by PierreR**
Paved the way toward #24

### CODE REVIEW

**Comment by diogob** [comment]
Thanks for the PR 🎉 

Unfortunately we still do not have any test coverage for this part of the code. I'm glad to merge as is next week (right now I don't have access to a development environment).
In the meantime, if you feel like adding some tests for the JWK that would be awesome!

**Comment by PierreR** [comment]
@diogob I have added a simple test case. These tests don't seem to be run by circleci (at least in PRs)?

**Comment by diogob** [comment]
@PierreR yes, there seems to be a problem with the circleci testing on PRs. I'll check this during the coming weekend. Thanks for adding the test case :D

**Comment by diogob** [comment]
@PierreR thanks again for the PR. I have verified the tests and the sample client in my local machine and everything seems fine (I just had to update the key to be longer).

**Pull request merged**
